version: '3.8'
services:
  web:
    image: elijahngocho/my-node-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydb

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    depends_on:
      - web
    environment:
      - REACT_APP_API_URL=http://web:3000

volumes:
  postgres_data: